## My notes

I decided to take the original data analysis project I completed with Danielle Steede and redo it/improve on the original version as well as take my analysis a little farther than the original. 

In this notebook I did all of my major cleaning and took some time to understand the data in each set. By the end of the file we have a pkl and csv of one big data frame with the relevant info from 2013-2022.

In [1]:
import pandas as pd
from Biz_Set_Functions import *

In [2]:
#loading dfs, adding year column and standardizing column titles
df13 = made_df('Data Sets/cbp13pr_mun.csv', 2013)
df14 = made_df('Data Sets/cbp14pr_mun.csv', 2014)
df15 = made_df('Data Sets/cbp15pr_mun.csv', 2015)
df16 = made_df('Data Sets/cbp16pr_mun.csv', 2016)
df17 = made_df('Data Sets/cbp17pr_co.csv', 2017)
df18 = made_df('Data Sets/cbp_pr_mun_2018.csv', 2018)
df19 = made_df('Data Sets/cbp_pr_mun_2019.csv', 2019)

files = ['Data Sets/2020-1.csv','Data Sets/2020-2.csv','Data Sets/2020-3.csv','Data Sets/2020-4.csv']
df20 = combined_df(files, 2020)

files21 = ['Data Sets/_lmi_excel_QCEW_2021_Composición Industrial Municipio 1.csv',
           'Data Sets/_lmi_excel_QCEW_2021_Composición Industrial Municipio 2.csv',
          'Data Sets/_lmi_excel_QCEW_2021_Composición Industrial Municipio 3.csv',
          'Data Sets/_lmi_excel_QCEW_2021_Composición Industrial Municipio 4.csv']
df21 = combined_df(files21, 2021)

files22= ['Data Sets/2022_1.csv',
         'Data Sets/2022_2.csv',
         'Data Sets/2022_3.csv',
         'Data Sets/2022_4.csv']
df22 = combined_df(files22, 2022)

In [3]:
#concat
df13_19 = pd.concat([df13,df14,df15,df16,df17,df18,df19])
df13_19

df20_22 = pd.concat([df20,df21,df22])
df20_22

#translating and renaming columns

def rename_columns(x):
    new_names={'industria':'industry','cty':'town_code','municipio':'town_name','unidades':'establishments',
               'empleo promedio':'average_employment','promedio':'average','est':'establishments','fipscty':'town_code'}
    x.columns=x.columns.str.strip()
    x.rename(columns=new_names, inplace=True)
    return x

df12_19 = rename_columns(df13_19)
df20_22 = rename_columns(df20_22)

#final concat
df13_22 = pd.concat([df13_19, df20_22], axis = 0)
df13_22

,fipstate,town_code,naics,empflag,emp_nf,emp,qp1_nf,qp1,ap_nf,ap,...,unnamed: 24,unnamed: 25,unnamed: 26,salrio total municipio segundo trimestre 2019,salrio total municipio primer trimestre 2021,salrio total municipio tercer trimestre 2021,salrio total municipio cuarto trimestre 2021,salrio total municipio primr trimestre 2022,salario total municipio segundo trimestre 2022,salario total municipio tercer trimestre 2022
0,72.0,1,------,NaN,G,706.0,G,2672.0,G,10719.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,72.0,1,23----,B,D,0.0,D,0.0,D,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,72.0,1,236///,A,D,0.0,D,0.0,D,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,72.0,1,2361//,A,D,0.0,D,0.0,D,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,72.0,1,23611/,A,D,0.0,D,0.0,D,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13755,NaN,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
13756,NaN,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
13757,NaN,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
13758,NaN,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
13759,NaN,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
#dropping unneeded columns


columns_to_drop = ['fipstate','empflag', 'emp_nf', 'emp', 'qp1_nf',
                   'qp1', 'ap_nf', 'ap', 'n1_4', 'n5_9', 'n10_19', 'n20_49',
                   'n50_99', 'n100_249', 'n250_499', 'n500_999', 'n1000', 'n1000_1',
                   'n1000_2', 'n1000_3', 'n1000_4', 'censtate', 'cencty', 'unnamed: 10', 'unnamed: 11',
                   'unnamed: 12', 'unnamed: 13', 'unnamed: 14', 'unnamed: 15',
                   'unnamed: 16', 'unnamed: 17', 'unnamed: 18', 'unnamed: 19',
                   'unnamed: 20', 'unnamed: 21', 'unnamed: 22', 'unnamed: 23',
                   'unnamed: 24', 'average_employment','salrio total municipio cuarto trimestre 2021',
                   'salrio total municipio tercer  trimestre 2021','salrio total municipio primer trimestre 2021',
                   'salrio total municipio primr trimestre 2022','salario total municipio segundo trimestre 2022',
                   'salario total municipio tercer trimestre 2022','average_employment',
                   'salrio total municipio segundo trimestre 2019','salario total','unnamed: 8','unnamed: 9',
                   'unnamed: 25','unnamed: 26','n<5','average','industry']

df13_22.drop(columns = columns_to_drop, inplace=True)

df13_22

       town_code   naics establishments  year      town_name
0              1  ------            130  2013            NaN
1              1  23----              8  2013            NaN
2              1  236///              5  2013            NaN
3              1  2361//              5  2013            NaN
4              1  23611/              5  2013            NaN
...          ...     ...            ...   ...            ...
13755        999     NaN              0  2022  No Codificado
13756        999     NaN              0  2022  No Codificado
13757        999     NaN              0  2022  No Codificado
13758        999     NaN              0  2022  No Codificado
13759        999     NaN              0  2022  No Codificado

[210488 rows x 5 columns]

In [5]:
df13_22.info()

<class 'pandas.core.frame.DataFrame'>
Index: 210488 entries, 0 to 13759
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   town_code       210488 non-null  int64
 1   naics           209103 non-null  object
 2   establishments  210488 non-null  object
 3   year            210488 non-null  int64
 4   town_name       41280 non-null   object
dtypes: int64(2), object(3)
memory usage: 9.6+ MB

In [6]:
#updating column dtypes
df13_22["establishments"]=pd.to_numeric(df13_22["establishments"], errors='coerce')
df13_22['year'] = df13_22['year'].astype(int)

In [7]:
#dropping null rows based on columns
df13_22.dropna(subset=['naics','establishments'], inplace=True)
df13_22.isna().sum()

town_code              0
naics                  0
establishments         0
year                   0
town_name         169208
dtype: int64

In [8]:
df13_22 = df13_22[~((df13_22['town_name'].isin(['No Codificado', 'Multi Municipio', 'Statewide'])) | 
                    (df13_22['naics'] == '------'))]

df13_22['town_name'].replace('nan',None,inplace=True)

C:\Users\NessaJay\AppData\Local\Temp\ipykernel_22604\197052235.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13_22['town_name'].replace('nan',None,inplace=True)

In [9]:
df13_22['town_name'].value_counts(dropna=False)

town_name
NaN          168655
Maunabo         505
Patillas        505
Orocovis        505
Naranjito       505
              ...
Corozal         505
Comerío         505
Coamo           505
Yauco           505
San Juan        483
Name: count, Length: 79, dtype: int64

In [10]:
#standardizing naics column. We just want to look at overall industry, not get into the nitty gritty subcategories

def replace_naics(naics_code):
    # Dictionary mapping NAICS codes to industry names
    naics_dict = {
    "11": "11","21": "21","22": "22","23": "23","31": "31","32": "32","33": "33","42": "42","44": "44","45": "45",
    "48": "48","49": "49","51": "51","52": "52","53": "53","54": "54","55": "55","56": "56","61": "61","62": "62","71":"71",
    "72": "72","81": "81","92": "92"
}
    
    industry_code = naics_code[:2]  # Extract first two digits of NAICS code
    return naics_dict.get(industry_code, "00")


df13_22['naics'] = df13_22['naics'].apply(replace_naics)

C:\Users\NessaJay\AppData\Local\Temp\ipykernel_22604\791782819.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13_22['naics'] = df13_22['naics'].apply(replace_naics)

In [33]:
df13_22['naics'] = pd.to_numeric(df13_22['naics'])

#dropping rows of the bottom industries that are tiny
df13_22 = df13_22[~df13_22['naics'].isin([61, 51, 71, 49, 21, 55, 22, 11, 92,0])]

In [29]:
#we decided to group the towns by region to make graphing much more streamlined
df13_22['region'] = replace_town_with_region(df13_22,'town_code')

#making sure all towns labeled accurately
df13_22['town_name'] = replace_code_with_town(df13_22, 'town_code')

#resetting the index
df13_22 = df13_22.reset_index(drop=True)

In [34]:
# Pickle the DataFrame to use elsewhere
df13_22.to_pickle('full_clean_df.pkl')

# Step 1: Load the DataFrame from the pickle file
df = pd.read_pickle('full_clean_df.pkl')

# Step 2: Save the DataFrame to a CSV file
df.to_csv('pr_biz_dataset_clean.csv', index=False)